### ISSUE TITLE
Al dar click en botón Agregar artista en la página principal, la siguiente interface tiene como título 'Agregar álbum'

### ISSUE THREAD

**Issue by ofgarzon2662** [johabeltran88/appsMoviles_Miso#61]
**COMPORTAMIENTO ESPERADO**

Se espera que en el formulario para agregar un artista se observe en el título del mismo "Agregar Artista"

**COMPORTAMIENTO ACTUAL**

Actualmente el título del formulario para agregar artista se encuentra como "Agregar Álbum"

**PASOS PARA REPRODUCIR DEFECTO**

1. Entrar como Coleccionista
2. Dar clic sobre el botón "Agregar Artista"

**EVIDENCIAS**

A continuación se observa una foto de la inconsistencia
![Screenshot_20231027-184458](https://github.com/johabeltran88/appsMoviles_Miso/assets/5341117/bf2bc0ee-b999-4528-8f69-ffcc2c66a1c2)

A continuación se observa un video de la inconsistencia
https://drive.google.com/file/d/1JOM9b-ASIB9EKkPv1xSDkuijpFEwHQnT/view?usp=sharing

**CONTEXTO**
Sistema operativo. Android

**INFORMACIÓN ADICIONAL**
N/A

**Comment by Esteban1099** [comment]
Ajustado
