### ISSUE TITLE
La fecha de nacimiento de un artista no cumple con el formato permitido por el API Rest

### ISSUE THREAD

**Issue by johabeltran88** [johabeltran88/appsMoviles_Miso#63]
**COMPORTAMIENTO ESPERADO**

Se espera que el formato de la fecha de nacimiento de un artista sea MM/dd/yyyy, debido a que es el formato permitido por la API Rest entregada para el proyecto.

**COMPORTAMIENTO ACTUAL**

Actualmente el formato permitido desde la pantalla del teléfono es dd/MM/yyyy, sin embargo al darle clic en guardar se presenta un error; esto solo se presenta para días mayores a 12, ya que si el día se coloca menor a 12 entonces el backend lo toma como mes.

**PASOS PARA REPRODUCIR DEFECTO**

A continuación se observa un video de la inconsistencia encontrada
https://github.com/johabeltran88/appsMoviles_Miso/assets/124108568/daa5df04-e6b6-4a44-be5a-1cd4f7cc9c38

**EVIDENCIAS**

A continuación se observa una foto de la inconsistencia
![Error](https://github.com/johabeltran88/appsMoviles_Miso/assets/124108568/886b4a2d-118a-434b-b7ac-624a018fdcc2)

**CONTEXTO**
Sistema operativo. Android

**INFORMACIÓN ADICIONAL**
N/A

**Comment by Esteban1099** [comment]
Ajustado
