### ISSUE TITLE
HU07 - Crear un álbum

### ISSUE THREAD

**Issue by mamartinezp123** [johabeltran88/appsMoviles_Miso#8]
Como coleccionista quiero agregar un álbum al listado

Criterios de aceptación

* Desde la pantalla de un coleccionista, debe existir un botón de agregar un álbum
* Al darle clic al botón de agregar álbum, se debe cambiar a la pantalla que contiene el formulario de agregar álbum
* El formulario de agregar álbum debe tener los campos de nombre, imagen del álbum, fecha de lanzamiento, descripción, género y disquera.
* Todos los campos del formulario son obligatorios, si no se completa alguno debe indicarle al usuario cual campo falta por completar
* El nombre será una cadena de máximo 50 caracteres
* La descripción será una cadena de máximo 500 caracteres
* La imagen del álbum debe ser una URL válida
* La fecha de lanzamiento debe ser un campo de tipo fecha
* El campo género debe ser una lista desplegable con las opciones Classical, Salsa, Rock y Folk
* El campo disquera debe ser una lista desplegable Sony Music, EMI, Discos Fuentes, Elektra y Fania Record
* El formulario debe tener un botón agregar, que al dar tab debe agregar el álbum al listado.
* El formulario debe tener un botón cancelar, que al dar tab debe volver a la pantalla inicial del usuario correspondiente

Mock up

![Image](https://github.com/johabeltran88/appsMoviles_Miso/assets/124101154/181283e8-0466-4559-97ed-d4ffd4cc3ea9)

PUNTAJE: 8

**Comment by ofgarzon2662** [comment]
Historia exitosamente terminada.
